name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.252.126.11 >> ~/.ssh/known_hosts

      - name: Install dependencies and deploy
        run: |
          ssh-agent bash -c 'ssh-add ~/.ssh/id_rsa && ssh -o StrictHostKeyChecking=no mf4vad6qmw1k@198.12.235.72 "cd /path/to/your/project && git pull origin master && composer update --ignore-platform-req=php --no-interaction --no-progress && php artisan optimize:clear"'
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
